# по какой-то причине падает проверка на здоровье по localhost, пришлось вернуть предыдущий вариант
services:
  metamodel:
    build:
      context: metamodel
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost/root.yaml || exit 1"]
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 1s
    volumes:
      - ./metamodel/metamodel:/metamodel
      # - ./metamodel/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"

  manifest:
    build:
      context: manifest
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost/root.yaml || exit 1"]
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 1s
    volumes:
      - ./manifest/manifest:/manifest
      # - ./manifest/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8082:80"

  plantuml:
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/plantuml/svg/Iyv9B2vMA4ajBW40 || exit 1"]
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 1s
    image: seaf/plantuml-server:jetty
    ports:
      - 9000:8080
    environment:
      - BASE_URL=plantuml

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      VUE_APP_DOCHUB_MODE: backend
      VUE_APP_DOCHUB_DATALAKE_CACHE: memory
      VUE_APP_DOCHUB_BACKEND_PORT: 80
      VUE_APP_DOCHUB_METAMODEL: http://metamodel/root.yaml
      VUE_APP_DOCHUB_ROOT_MANIFEST: http://manifest/root.yaml
      VUE_APP_DOCHUB_APPEND_DOCHUB_DOCS: y
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost/core/storage/jsonata/%28%24.swamphub%29 || exit 1"]
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 5s
    depends_on:
      metamodel:
        condition: service_healthy
      manifest:
        condition: service_healthy
    ports:
      - "3030:80"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    # volumes:
    #   - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    environment:
      # т.к. это будет использоваться в браузере, поэтому нужен внешний URL 
      # ссылаемся на себя же, в nginx проксируемся в backend
      NGINX_BACKEND_LOCATION: http://backend

      VUE_APP_DOCHUB_BACKEND_URL: http://localhost:8080/ # прямой ход в backend - http://localhost:3030
      VUE_APP_DOCHUB_ROOT_DOCUMENT: swamp.welcome
      VUE_APP_PLANTUML_SERVER: http://localhost:9000/plantuml/svg/
      VUE_APP_DOCHUB_RENDER_CORE: ELK
    depends_on:
      backend:
        condition: service_healthy            
      plantuml:
        condition: service_healthy
    ports:
      - "8080:80"